import { router } from 'expo-router';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { Screen } from '@/core/components/Screen';
import { PrimaryButton } from '@/core/components/PrimaryButton';
import { SurfaceCard } from '@/core/components/SurfaceCard';
import { SectionTitle } from '@/core/components/SectionTitle';
import { colors, radius, spacing, touchTarget } from '@/core/theme/tokens';
import { typography } from '@/core/theme/typography';
import { demoToday } from '@/data/demo/demoData';
export function HomeScreen(){return <Screen><View style={styles.header}><View><Text style={styles.eyebrow}>GOOD AFTERNOON</Text><Text style={styles.title}>Today's workout</Text></View><Pressable accessibilityLabel="Settings" onPress={()=>router.push('/settings')} style={styles.settings}><Text style={styles.settingsText}>⚙</Text></Pressable></View><Text style={styles.cycle}>{demoToday.cycle}</Text><SurfaceCard style={styles.workoutCard}><SectionTitle>Today's plan</SectionTitle><Text style={styles.workoutName}>{demoToday.name.toUpperCase()}</Text><Text style={styles.metadata}>{demoToday.environmentName} · {demoToday.durationMinutes} min · {demoToday.exerciseCount} exercises</Text><View style={styles.selectorRow}><View style={styles.selector}><Text style={styles.selectorLabel}>ENVIRONMENT</Text><Text style={styles.selectorValue}>Fitness Hut ▾</Text></View><View style={styles.selector}><Text style={styles.selectorLabel}>TIME</Text><Text style={styles.selectorValue}>45 min ▾</Text></View></View><PrimaryButton label="START WORKOUT" onPress={()=>router.push('/workout/workout_pull/preview')}/></SurfaceCard><SectionTitle>Last workout</SectionTitle><SurfaceCard><Text style={styles.lastName}>{demoToday.lastWorkout.name}</Text><Text style={styles.metadata}>{demoToday.lastWorkout.metadata}</Text></SurfaceCard></Screen>}
const styles=StyleSheet.create({header:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},eyebrow:{...typography.labelCaps,color:colors.primary},title:{...typography.display,color:colors.textPrimary},settings:{width:touchTarget,height:touchTarget,borderRadius:radius.pill,alignItems:'center',justifyContent:'center',backgroundColor:colors.surfaceHigh},settingsText:{fontSize:20,color:colors.textPrimary},cycle:{...typography.bodySmall,color:colors.textSecondary},workoutCard:{gap:spacing.md},workoutName:{...typography.display,fontSize:28,color:colors.textPrimary},metadata:{...typography.bodySmall,color:colors.textSecondary},selectorRow:{flexDirection:'row',gap:spacing.sm},selector:{flex:1,borderWidth:1,borderColor:colors.outlineVariant,borderRadius:radius.sm,padding:spacing.sm},selectorLabel:{...typography.labelCaps,color:colors.textSecondary},selectorValue:{...typography.body,color:colors.textPrimary,marginTop:4},lastName:{...typography.headline,color:colors.textPrimary}});
