import { router } from 'expo-router';
import { StyleSheet, Text, TextInput } from 'react-native';
import { Screen } from '@/core/components/Screen';
import { PrimaryButton } from '@/core/components/PrimaryButton';
import { SurfaceCard } from '@/core/components/SurfaceCard';
import { colors, spacing } from '@/core/theme/tokens';
import { typography } from '@/core/theme/typography';
const results=[['Lat Pulldown',['40 kg × 12','40 kg × 11','37.5 kg × 12']],['Low Row',['37.5 kg × 12','37.5 kg × 12','37.5 kg × 11']]] as const;
export function WorkoutCompleteScreen(){return <Screen contentStyle={styles.content}><Text style={styles.check}>✓</Text><Text style={styles.kicker}>WORKOUT COMPLETE</Text><Text style={styles.title}>Back + Biceps</Text><Text style={styles.meta}>52 min · 5 exercises · 15 working sets · Fitness Hut</Text>{results.map(([name,sets])=><SurfaceCard key={name}><Text style={styles.exercise}>{name}</Text>{sets.map((set,index)=><Text key={set} style={styles.set}>Set {index+1}    {set}</Text>)}</SurfaceCard>)}<Text style={styles.showMore}>SHOW 3 MORE</Text><Text style={styles.label}>WORKOUT NOTES</Text><TextInput multiline placeholder="How did the workout feel?" placeholderTextColor={colors.outline} style={styles.notes}/><PrimaryButton label="FINISH" onPress={()=>router.replace('/')}/></Screen>}
const styles=StyleSheet.create({content:{paddingBottom:40},check:{fontSize:38,color:colors.success,textAlign:'center'},kicker:{...typography.labelCaps,color:colors.success,textAlign:'center'},title:{...typography.display,color:colors.textPrimary,textAlign:'center'},meta:{...typography.bodySmall,color:colors.textSecondary,textAlign:'center',marginBottom:spacing.sm},exercise:{...typography.headline,color:colors.textPrimary,marginBottom:spacing.xs},set:{...typography.dataSmall,color:colors.textSecondary,marginTop:4},showMore:{...typography.labelCaps,color:colors.primary,textAlign:'center',paddingVertical:spacing.sm},label:{...typography.labelCaps,color:colors.textSecondary},notes:{minHeight:96,borderWidth:1,borderColor:colors.outlineVariant,backgroundColor:colors.surface,color:colors.textPrimary,padding:spacing.md,textAlignVertical:'top'}});
